name: Update Dojo

on: push

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: pwncollege/dojo-update@v1
        with:
          dojo: tesuji~7893c9ad
          update_code: ${{ secrets.UPDATE_CODE }}
